# Use the official Ubuntu image as the base image
FROM ubuntu:22.04

# Install necessary tools
RUN apt update && \
    apt -y install sudo 

#curl 
RUN sudo apt install curl -y

# Install AWS CLI dependencies
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip

# Install AWS CLI using pip
RUN pip3 install --upgrade awscli


# Clean up the package cache to reduce image size
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Update package lists and install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget unzip git make && \
    rm -rf /var/lib/apt/lists/*

# Download and install Terraform
# RUN wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip && \
#     unzip terraform_1.7.0_linux_amd64.zip && \
#     mv terraform /usr/local/bin/ && \
#     rm terraform_1.7.0_linux_amd64.zip

# Download and install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip && \
    unzip terraform_1.6.6_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_1.6.6_linux_amd64.zip


WORKDIR /pipeline
COPY . /pipeline