# Use the official Ubuntu image as the base image
FROM ubuntu:22.04

# Install necessary tools
RUN apt update && \
    apt -y install sudo 

# Install curl
RUN sudo apt install curl -y

# Install Google Cloud SDK dependencies
RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip \
    gnupg

# Install Google Cloud SDK using apt
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    sudo apt-get update && sudo apt-get install -y google-cloud-sdk

# Clean up the package cache to reduce image size
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Update package lists and install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget unzip git make && \
    rm -rf /var/lib/apt/lists/*

# Download and install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip && \
    unzip terraform_1.6.6_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_1.6.6_linux_amd64.zip

WORKDIR /pipeline
COPY . /pipeline